app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

Route::filter('ACL', 'Mebius\Filter\AclPermittedFilter');

Route::when('*', 'csrf', ['post', 'put', 'delete']);

Route::group(['before' => 'auth'],
    function () {
    Route::get('/',
        ['as' => 'main',
      'uses' => 'Mebius\Controller\MainController@indexAction'
    ]);
    Route::get('logout',
        ['as' => 'logout',
      'uses' => 'Mebius\Controller\AuthController@getLogout']);
    Route::put('auth/settings',
        ['as' => 'auth.settings.put',
      'uses' => 'Mebius\Controller\AuthController@putSettings']);
    Route::get('auth/settings',
        ['as' => 'auth.settings.get',
      'uses' => 'Mebius\Controller\AuthController@getSettings']);
    #####################
    ## ACL
    Route::group(['before' => 'ACL'],
        function () {
        #####################
        ## Entry
        Route::match(['GET', 'POST'], 'entry/search',
            ['as' => 'entry.search',
          'uses' => 'Mebius\Controller\EntryController@search']);
        Route::put('entry/{entry}/status',
            ['as' => 'entry.status',
          'uses' => 'Mebius\Controller\EntryController@status']);
        Route::get('entry/export',
            ['as' => 'entry.export',
          'uses' => 'Mebius\Controller\EntryController@export']);
        Route::get('entry/{entry}/showlogs',
            ['as' => 'entry.showlogs',
          'uses' => 'Mebius\Controller\EntryController@showlogs']);
        Route::resource('entry', 'Mebius\Controller\EntryController');
        ###############
        ## Order
        Route::match(['GET', 'POST'], 'order/search',
            ['as' => 'order.search',
          'uses' => 'Mebius\Controller\OrderController@search']);
        Route::get('order/export',
            ['as' => 'order.export',
          'uses' => 'Mebius\Controller\OrderController@export']);
        Route::post('order/{order}/finish',
            ['as' => 'order.finish',
          'uses' => 'Mebius\Controller\OrderController@finish']);
        Route::get('order/{order}/status/{status}',
            ['as' => 'order.status.get',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::put('order/{order}/status/{status}',
            ['as' => 'order.status.put',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::get('order/{order}/showlogs',
            ['as' => 'order.showlogs',
          'uses' => 'Mebius\Controller\OrderController@showlogs']);
        Route::post('order/{order}/cancel',
            ['as' => 'order.cancel',
          'uses' => 'Mebius\Controller\OrderController@cancel']);
        Route::post('order/{order}/archivate',
            ['as' => 'order.archivate',
          'uses' => 'Mebius\Controller\OrderController@archivate']);
        Route::post('order/{order}/stuff',
            ['as' => 'order.stuff',
          'uses' => 'Mebius\Controller\OrderController@stuff']);
        // Добавление денег в кассу
        Route::post('order/{order}/cashbox',
            ['as' => 'order.cashbox',
          'uses' => 'Mebius\Controller\OrderController@cashbox']);
        Route::resource('order', 'Mebius\Controller\OrderController');
        #####################
        ## User
        Route::resource('user', 'Mebius\Controller\UserController');
        #####################
        ## Role
        Route::resource('role', 'Mebius\Controller\RoleController');
        #####################
        ## Refer
        Route::resource('refer', 'Mebius\Controller\ReferController');
        #####################
        ## Cashbox
        Route::get('cashbox',
            ['as' => 'cashbox.index',
          'uses' => 'Mebius\Controller\CashboxController@getIndex']);
        Route::get('cashbox/export',
            ['as' => 'cashbox.export',
          'uses' => 'Mebius\Controller\CashboxController@export']);
        Route::get('cashbox/{order}',
            ['as' => 'cashbox.show',
          'uses' => 'Mebius\Controller\CashboxController@show']);
        #####################
        ## Report
        Route::get('report',
            ['as' => 'report.index',
          'uses' => 'Mebius\Controller\ReportController@getIndex']);
        Route::get('report/export',
            ['as' => 'report.export',
          'uses' => 'Mebius\Controller\ReportController@export']);
        #####################
        ## Help
        Route::get('help',
            ['as' => 'help.index',
          'uses' => 'Mebius\Controller\HelpController@getIndex']);
    });
});
Route::post('login', 'Mebius\Controller\AuthController@postLogin');
Route::get('login',
    ['as' => 'login', 'uses' => 'Mebius\Controller\AuthController@showLogin']);

app/models/Order.php
<?php

use Illuminate\Database\Eloquent\Relations\HasMany;
use Mebius\Model\Contracts\OrderInterface;
use Mebius\Model\OptionedModel;

class Order extends OptionedModel implements OrderInterface
{

    protected $table = 'orders';
    protected $primaryKey = 'order_key';

    /**
     *
     */
    const ORDER_KEY = 'order_key';
    const FINISH_DATE = 'finish_date';
    const FINISHED_TIME = 'finished_time';
    const ARCHIVED_AT = 'archived_at';

    /**
     *
     */
    const STATUS_ACTIVE = 'CREATED';
    const STATUS_FINISHED = 'FINISHED';
    const STATUS_ARCHIVED = 'ARCHIVED';

    /**
     *
     */
    const TYPE_DATE = 'date';
    const TYPE_STRING = 'string';
    const TYPE_PHONE = 'phone';

    /* protected $STATUSES = [
      'FINISHED' => 'FINISHED',
      ]; */

    protected $isLoggable = true;
    protected $noLogFields = [
      Order::FINISHED_TIME,
      'updated_by',
    ];
    protected $relationsKeys = [
      'user_id' => 'master',
      'refer_id' => 'refer',
      'supplier_id' => 'supplier',
    ];

    /**
     * The attributes that should be hidden for arrays.
     * @var array
     */
    protected $hidden = [
      'refer_id',
      'created_by',
      'updated_by',
    ];

    /**
     *
     * @var array
     */
    protected $guarded = [];

    /**
     *
     * @var array
     */
    protected $fillable = [
      'order_key',
      'title',
      'client_name',
      'client_phone',
      'metro',
      'mo_town',
      'descr',
      'details',
      'supplier_id',
      'refer_id',
      'cashless',
      'inplace',
      'cost',
      'prepay',
      'result_amount',
      'cashbox',
      'comment',
      'docs_signed',
      Order::FINISH_DATE,
      'created_by', // чтоб можно было мастера менять
    ];

    /* Array

      [photo] => Array
      (
      [0] =>
      )

      ) */

    /**
     *
     * @var array
     */
    protected static $rules = [
      'order_key' => ['required', 'regex:/^\w\-\d{5,6}\-\d+$/ui'],
      'title' => ['required', 'regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:100'],
      'client_name' => ['required', 'regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:200'],
      'client_phone' => ['required', 'regex:/^[\d\+\-\(\) ]{11,18}$/ui'],
      'metro' => ['regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:40'],
      'mo_town' => ['regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:50'],
      'descr' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      'details' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      'supplier_id' => ['numeric', 'exists:users,id'],
      'refer_id' => ['numeric', 'exists:refers,id'],
      'cashless' => ['integer', 'in:0,1'],
      'inplace' => ['integer', 'in:0,1'],
      'docs_signed' => ['integer', 'in:0,1'],
      'cost' => ['required', 'numeric'],
      'prepay' => ['numeric'],
      'cashbox' => ['numeric'],
      'result_amount' => ['numeric'],
      'comment' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      Order::FINISH_DATE => ['required', 'date'],
    ];

    /**
     * Поля сокращенной выборки
     * @var array
     */
    protected $shortStatement = [
      'order_key',
      'title',
      'client_name',
      'client_phone',
      'metro',
      'mo_town',
      'descr',
      'details',
      'supplier_id',
      'refer_id',
      'cashless',
      'inplace',
      'cost',
      'prepay',
      'result_amount',
      'cashbox',
      'comment',
      'docs_signed',
      Order::FINISH_DATE,
      'status',
      'created_by',
    ];

    protected static function boot()
    {
        static::creating(function($order) {
            static::$rules['order_key'][] = 'unique:orders';
        });

        static::updating(function($order) {

        });

        parent::boot();

        static::creating(function($order) {
            //echo '<pre>', print_r($order->toArray()), '</pre>';
            //die();
            $order->created_by = Auth::user()->id;
            $order->updated_by = Auth::user()->id;
        });

        static::updating(function($order) {
            $order->updated_by = Auth::user()->id;
        });
    }

    public function master()
    {
        return $this->hasOne('User', 'id', 'created_by');
    }

    public function supplier()
    {
        return $this->hasOne('User', 'id', 'supplier_id');
    }

    public function operator()
    {
        return $this->hasOne('User', 'id', 'operator_id');
    }

    public function updater()
    {
        return $this->hasOne('User', 'id', 'updated_by');
    }

    public function refer()
    {
        return $this->hasOne('Refer', 'id', 'refer_id');
    }

    /**
     *
     * @return HasMany
     */
    public function stuff()
    {
        return $this->hasMany('Stuff', 'order_id', 'id');
    }

    public function payments()
    {
        return $this->hasMany('Payment', 'order_id', 'id');
    }

    public function setMasterId($id)
    {
        $this->attributes['created_by'] = $id;
    }

    public function setClientPhoneAttribute($phone)
    {
        $this->attributes['client_phone'] = sanitize_phone($phone);
    }

    public function setDescrAttribute($descr)
    {
        //echo '<h1>SETTED</h1>';
        $this->attributes['descr'] = trim($descr);
    }

    public function getIsFinishedAttribute()
    {
        return isset($this->attributes['finished_time']) && strtotime($this->attributes['finished_time']) > 0;
    }

    public function getIsCanceledAttribute()
    {
        return isset($this->attributes['canceled_at']) ? !is_null($this->attributes['canceled_at'])
                : null;
    }

    public function getIsArchivedAttribute()
    {
        return $this->attributes['status'] == self::STATUS_ARCHIVED;
    }

    public function getIsActiveAttribute()
    {
        return $this->attributes['status'] == self::STATUS_ACTIVE;
    }

    public function getMasterIssetAttribute()
    {
        if ($this->exists) {
            return !is_null($this->master);
        }
    }

    public function getMasterNameAttribute()
    {
        if ($this->master_isset) {
            return $this->master->name;
        }
    }

    public function getIsOverdueAttribute()
    {
        return $this->is_active && date('Ymd',
                strtotime($this->getAttribute(Order::FINISH_DATE))) < date('Ymd');
    }

    public function getOrderKeyPrintAttribute()
    {
        return preg_replace('/(\d\d\d\d)(\d\d)(\-)(\d+)/',
            "<b>$1</b>$2$3<b>$4</b>", $this->order_key);
    }

    public function getCanBeClosedAttribute()
    {
        return $this->is_finished;
    }

    /**
     * Добавление суммы в кассу
     * @param int $int добавляемая сумма в кассу
     */
    public function addToCashBox($int)
    {
        $this->attributes['cashbox'] += $int;
    }

    /**
     *
     * @param int $timestamp
     */
    public function setArchivedAt($timestamp = false)
    {
        if ($timestamp === false) {
            $timestamp = time();
        }
        if ($this->exists) {
            $this->archived_at = date(static::getDateTimeFormat(), $timestamp);
        }
    }

    /**
     * Вычисляемое значение района заказа
     * @return int
     */
    public function getLocationAttribute()
    {
        $loc = '';
        if ($this->metro) {
            $loc .= 'м.' . $this->metro . ' ';
        }
        if ($this->mo_town) {
            $loc .= 'г.' . $this->mo_town;
        }
        if (!$loc) {
            $loc = '-';
        }
        return $loc;
    }

    /**
     * Вычисляемое значение долга мастера в кассу
     * (полученные, но не сданные деньги)
     * @return int
     */
    public function getCashboxMasterDebtAttribute()
    {
        return $this->prepay + $this->result_amount - $this->cashbox;
    }

    /**
     * Вычисляемое значение долга в кассу
     * @return int
     */
    public function getCashboxDebtAttribute()
    {
        //echo 'getCashboxDebtAttribute ' . ($this->cost - $this->cashbox);
        return $this->cost - $this->cashbox;
    }

    /**
     * Имеется-ли долг в кассу
     * @return boolean
     */
    public function getHasCashboxDebtAttribute()
    {
        return $this->cashbox_debt > 0;
    }

    /**
     * Вычисляемое значение долга клиента
     * @return int
     */
    public function getDebtAttribute()
    {
        return $this->cashbox_debt;
    }

    /**
     * Вычисляемое значение долга клиента
     * @return int
     */
    public function getClientDebtAttribute()
    {
        if ($this->is_cashless) {
            return $this->cashbox_debt;
        }
        return $this->cost - $this->prepay - $this->result_amount;
    }

    /**
     * Имеется-ли долг клиента
     * @return boolean
     */
    public function getHasClientDebtAttribute()
    {
        return $this->client_debt > 0;
    }

    /**
     * Имеется-ли долг клиента
     * @return boolean
     */
    public function getHasDebtAttribute()
    {
        return $this->debt > 0;
        //return ($this->has_client_debt || $this->cashbox_master_debt);
    }

    public function getIsCashlessAttribute()
    {
        //echo 'cashless ' . $this->attributes['cashless'];
        return $this->attributes['cashless'] > 0;
    }

    /* public function scopeOfMaster($query, $id)
      {
      return $query->whereCreatedBy($id);
      } */

    public function getTypeDateField($type)
    {
        switch ($type) {
            case 'new':
                return Order::CREATED_AT;
            case 'finish':
                return Order::FINISH_DATE;
            case 'finished':
                return Order::FINISHED_TIME;
            case 'overdue':
                return Order::FINISH_DATE;
            case 'refused':
                return Order::REFUSE_TIME;
            case 'archived':
                return Order::ARCHIVED_AT;
            default:
                return Order::CREATED_AT;
        }
    }

    public function getTypeOptions()
    {
        //$defaultTime = static::getDefaultDateTimeString();

        return [

app/views/order/show.blade.php
@extends('includes.extends_master')

{{-- Content --}}
@section('content')

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-{{ $order->getIcon() }}"></span>
            {{ $order->order_key_print }} / {{{ $order->master->name }}}
        </h3>
    </div>
    <div class="panel-body">

        <div style="padding-left:5px;">
            <small>
                {{ human_date($order->created_at, true) }}
            </small>
            <br/>
            <h4 style="margin-top:0;">
                {{{$order->title}}}
            </h4>

            @if($order->mo_town || $order->metro)
            <p style="margin-top:0;">
                @if($order->metro)
                <span class="text-info">
                    {{{ trans('msg.metro_pref').$order->metro.' ' }}}
                </span>
                @endif
                @if($order->metro && $order->mo_town)
                /
                @endif
                @if($order->mo_town)
                <span class="text-warning">
                    {{{ trans('msg.town_pref').$order->mo_town }}}
                </span>
                @endif
            </p>
            @endif

            @if($order->is_archived)
            <div class="alert alert-{{$order->finish_status}} alert-block">
                @if($order->is_canceled)
                {{ trans('status.canceled').' '.human_date_time($order->canceled_at, true) }}
                @else
                {{ trans('status.archived').' '.human_date_time($order->archived_at, true) }}
                @endif
            </div>
            @endif

            @if($order->is_finished && !$order->is_archived)
            <div class="alert alert-block alert-{{ $order->finish_status }}" style="margin:0">
                {{ trans('status.'.strtolower($order->status)).' '.human_date_time($order->finished_time, true) }}
                <br/>
            </div>
            @endif

            @if(!$order->is_archived && !$order->is_finished && $order->finish_status != 'success')
            <div class="alert alert-block alert-{{ $order->finish_status }}" style="margin:7px 0px 0px 3px;">

                {{ trans('order.finish_'.$order->finish_status) }}
                <br/>
                <b>{{{ strftime('%d %b %Y %A',strtotime($order->finish_date)) }}}</b>

            </div>
            @endif

            <br/>

            @if($order->descr)
            <p style="margin-top:10px;">
                <span class="glyphicon glyphicon-phone-alt"></span>
                <em>{{\nl2br($order->descr)}}</em>
            </p>
            @endif

            @if(!empty($order->details))
            <p>
                <span class="glyphicon glyphicon-question-sign"></span>
                <em>{{\nl2br($order->details)}}</em>
            </p>
            @endif

            @if(!empty($order->comment))
            <p>
                <span class="glyphicon glyphicon-info-sign"></span>
                <em>{{\nl2br($order->comment)}}</em>
            </p>
            @endif

        </div>

        <div class="well">

            <h4 style="margin:0 0 10px 2px;">
                {{{ $order->client_name }}}
            </h4>

            <a class="btn btn-success" href="tel:{{{ $order->client_phone }}}">
                <span class="glyphicon glyphicon-earphone"> </span>
                <span class="bfh-phone" data-format="<?= get_phone_format() ?>" data-number="{{$order->client_phone}}"></span>
            </a>
            <br/>

            @if(!$order->is_archived && !$order->is_finished && $order->finish_status == 'success')
            <p class="text-{{ $order->finish_status }}" style="margin:7px 0px 0px 3px;">

                {{ trans('order.finish_'.$order->finish_status) }}
                <br/>
                <b>{{{ strftime('%d %b %Y %A',strtotime($order->finish_date)) }}}</b>

            </p>
            @endif

        </div>

        <dl class="dl-horizontal details" style="margin-left:8px;">

            <dt>
            {{ trans('order.cost') }}
            </dt>
            <dd id="cost">
                <b>{{{ $order->cost.' '.$order->currency }}}</b>
                <br/>
                <span class="text-<?= $order->cashless ? 'danger' : 'success' ?>">
                    {{ $order->cashless ? trans('order.cashless') : trans('order.cash') }}
                </span>
            </dd>

            <dt>
            {{ trans('order.cashbox') }}
            </dt>
            <dd id="cashbox">
                @if(isset($routes['payments']))
                <a id="payments" href="{{ $routes['payments']['route'] }}" class="btn btn-default">
                    <span>{{ $order->cashbox }}</span> {{ $order->currency }}
                </a>
                @else
                <span>{{ $order->cashbox }}</span> {{ $order->currency }}
                @endif
            </dd>

            @if($order->has_debt)

            @if(!$order->cashless)

            <dt>
            {{ trans('order.prepay') }}
            </dt>
            <dd id="prepay">
                {{ $order->prepay ? $order->prepay.' '.$order->currency
                   .'<br/><small class="text-warning">'.human_date($order->created_at, true).'</small>' : trans('msg.no') }}
            </dd>

            @if($order->is_finished || $order->is_archived)

            @if($order->cashless)
            <dt>{{ trans('order.docs_signed') }}</dt>
            <dd>{{{ $order->docs_signed ? trans('msg.yes') : trans('msg.no') }}}</dd>
            @else
            <dt>{{ trans('order.result_amount') }}</dt>
            <dd id="result_amount">
                {{ $order->result_amount ? $order->result_amount.' '.$order->currency.'<br/><small class="text-warning">'.human_date($order->finished_time, true).'</small>' : trans('msg.no') }}
            </dd>
            <dt>
            {{ trans('order.client_debt') }}
            </dt>
            <dd>{{{ $order->client_debt.' '.$order->currency }}}</dd>
            @endif

            @endif

            <dt>
            {{ trans('order.cashbox_master_debt') }}
            </dt>
            <dd id="cashbox"><span>{{ $order->cashbox_master_debt }}</span> {{ $order->currency }}</dd>

            @endif

            <dt>
            {{ trans('order.cashbox_debt') }}
            </dt>
            <dd id="cashbox_debt"><span>{{ $order->cashbox_debt }}</span> {{ $order->currency }}</dd>

            @endif

            @if(route_allowed('refer.index'))
            <dt>
            <span class="glyphicon glyphicon-user"></span>
            Мастер
            </dt>
            <dd>
                @if(!$order->master_isset)
                {{ trans('msg.not_assigned') }}
                @else
                <a class="btn btn-success" href="tel:{{{ $order->master->phone }}}">
                    <span class="glyphicon glyphicon-earphone"> </span>
                    <span>{{ $order->master->name }}</span>
                </a>
                @endif
            </dd>
            @endif

            <dt>
            @if(isset($routes['stuff']) && !$order->is_finished)
            <button id="stuff-button" type="button" class="btn btn-default btn-large">
                <b>{{ trans('order.stuff') }}</b>
            </button>
            @else
            {{ trans('order.stuff') }}
            @endif
            </dt>
            <dd id="stuff-list">
                @if($order->stuff->count())
                <ul style="margin-top:7px;">
                    @foreach($order->stuff as $item)
                    <li>
                        {{ $item->name }} - {{ $item->quantity }}
                    </li>
                    @endforeach
                </ul>
                @else
                -
                @endif
            </dd>

        </dl>


        <div id="data-loading" class="well">
            <h4><img src="/img/ajax-loader.gif"/> {{ trans('msg.loading') }}</h4>
        </div>
        <div id="results" class="alert alert-block alert-success">
        </div>

        @if(isset($routes['stuff']))
        @include('order.inc.stuff')
        @endif

        @if(isset($routes['finish']))
        @include('order.inc.finishForm',['route' => $routes['finish']])
        @endif

        @if(isset($routes['cashbox']))
        @include('order.inc.cashbox',['routes' => $routes])
        @endif

        <div class="col-lg-3">

            @if(isset($routes['cashbox']))
            <a id="cashbox-button" type="button" class="btn btn-primary btn-block">{{$routes['cashbox']['name']}}</a>
            @endif

            @if(isset($routes['finish']))
            <a id="finish-button" type="button" class="btn btn-primary btn-block" href="#js">{{ $routes['finish']['name'] }}</a>
            @endif

            <!-- archiving-button -->
            @if(isset($routes['archivate']))
            {{ Form::postButton($routes['archivate'],
                trans('order.do_archived')." ".$order->order_key."?") }}
            @endif

            @if(isset($routes['edit']))
            <a id="edit-button" type="button" class="btn btn-primary btn-block" href="{{$routes['edit']['route']}}">
                {{ $routes['edit']['name'] }}
            </a>
            @endif

            @if(isset($routes['cancel']))
            {{ Form::postButton($routes['cancel'],
                trans('order.cancel-button-confirm'), 'default') }}
            @endif

        </div>

        <div class="row col-lg-12" style="margin-top:5px;">
            @if(isset($routes['showlogs']))
            @include('includes.showlogs',['route' => $routes['showlogs']])
            @endif
        </div>

    </div>
</div>

@if(isset($routes['order.index']))
<?php $route = $routes['order.index']; ?>
<a href="{{ $route->route }}" type="button" class="btn btn-default col-xs-12 col-lg-3">
    {{ $route->name }}
</a>
@endif
<br/>
<br/>

{{ HTML::script('/js/bootstrap-formhelpers-phone.js') }}

<script>
    $(document).ready(function () {

        close_all_forms();

        $(".reset").click(function () {
            close_all_forms();
        });

        $("#stuff-button").click(function () {
            close_all_forms();
            $("#stuff-form").show();
            $("#stuff-list").hide();
        });

        function close_all_forms() {
            $("#order-finish-form").hide();
            $("#order-cashbox-form").hide();
            $("#stuff-form").hide();
            $("#finish-button").show();
            $("#cancel-button").show();
            $("#cashbox-button").show();
            $('#data-loading').hide();
            $("#results").hide();
            $("#stuff-list").show();
        }

<?php if (isset($routes['cancel'])): ?>

            $("#cancel-button").click(function () {
                close_all_forms();
                if (confirm("<?= trans('msg.cancel-button-confirm') ?>")) {
                    $('#data-loading').show();
                    $(this).hide();
                    $.ajax({
                        type: "POST",
                        data: '_token=<?= csrf_token() ?>',
                        cache: false,
                        url: '<?= $routes['cancel']['route'] ?>',
                        success: function (data) {
                            if (data.error === false) {
                                $("#results").text("<?= trans('order.cancelled_ok') ?>")
                                        .removeClass('alert-danger')
                                        .addClass('alert-success')
                                        .show();
                            } else {
                                $("#results").text('<?= trans('order.an_error') ?>: ' + data.msg)
                                        .removeClass('alert-success')
                                        .addClass('alert-danger')
                                        .show();
                            }
                            $('#data-loading').hide();
                        },
                        error: function (jqXHR, textStatus) {
                            $("#results").html('<?= trans('order.an_error') ?>: ' + textStatus).show();
                            $('#data-loading').hide();
                            $("#cancel-button").show();
                        }
                    });
                    return false;
                }
            });
<?php endif; ?>
    });
</script>


@stop