app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

Route::filter('ACL', 'Mebius\Filter\AclPermittedFilter');

Route::when('*', 'csrf', ['post', 'put', 'delete']);

Route::group(['before' => 'auth'],
    function () {
    Route::get('/',
        ['as' => 'main',
      'uses' => 'Mebius\Controller\MainController@indexAction'
    ]);
    Route::get('logout',
        ['as' => 'logout',
      'uses' => 'Mebius\Controller\AuthController@getLogout']);
    Route::put('auth/settings',
        ['as' => 'auth.settings.put',
      'uses' => 'Mebius\Controller\AuthController@putSettings']);
    Route::get('auth/settings',
        ['as' => 'auth.settings.get',
      'uses' => 'Mebius\Controller\AuthController@getSettings']);
    #####################
    ## ACL
    Route::group(['before' => 'ACL'],
        function () {
        #####################
        ## Entry
        Route::match(['GET', 'POST'], 'entry/search',
            ['as' => 'entry.search',
          'uses' => 'Mebius\Controller\EntryController@search']);
        Route::put('entry/{entry}/status',
            ['as' => 'entry.status',
          'uses' => 'Mebius\Controller\EntryController@status']);
        Route::get('entry/export',
            ['as' => 'entry.export',
          'uses' => 'Mebius\Controller\EntryController@export']);
        Route::get('entry/{entry}/showlogs',
            ['as' => 'entry.showlogs',
          'uses' => 'Mebius\Controller\EntryController@showlogs']);
        Route::resource('entry', 'Mebius\Controller\EntryController');
        ###############
        ## Order
        Route::match(['GET', 'POST'], 'order/search',
            ['as' => 'order.search',
          'uses' => 'Mebius\Controller\OrderController@search']);
        Route::get('order/export',
            ['as' => 'order.export',
          'uses' => 'Mebius\Controller\OrderController@export']);
        Route::post('order/{order}/finish',
            ['as' => 'order.finish',
          'uses' => 'Mebius\Controller\OrderController@finish']);
        Route::get('order/{order}/status/{status}',
            ['as' => 'order.status.get',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::put('order/{order}/status/{status}',
            ['as' => 'order.status.put',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::get('order/{order}/showlogs',
            ['as' => 'order.showlogs',
          'uses' => 'Mebius\Controller\OrderController@showlogs']);
        Route::post('order/{order}/cancel',
            ['as' => 'order.cancel',
          'uses' => 'Mebius\Controller\OrderController@cancel']);
        Route::post('order/{order}/archivate',
            ['as' => 'order.archivate',
          'uses' => 'Mebius\Controller\OrderController@archivate']);
        Route::post('order/{order}/stuff',
            ['as' => 'order.stuff',
          'uses' => 'Mebius\Controller\OrderController@stuff']);
        // Добавление денег в кассу
        Route::post('order/{order}/cashbox',
            ['as' => 'order.cashbox',
          'uses' => 'Mebius\Controller\OrderController@cashbox']);
        Route::resource('order', 'Mebius\Controller\OrderController');
        #####################
        ## User
        Route::resource('user', 'Mebius\Controller\UserController');
        #####################
        ## Role
        Route::resource('role', 'Mebius\Controller\RoleController');
        #####################
        ## Refer
        Route::resource('refer', 'Mebius\Controller\ReferController');
        #####################
        ## Cashbox
        Route::get('cashbox',
            ['as' => 'cashbox.index',
          'uses' => 'Mebius\Controller\CashboxController@getIndex']);
        Route::get('cashbox/export',
            ['as' => 'cashbox.export',
          'uses' => 'Mebius\Controller\CashboxController@export']);
        Route::get('cashbox/{order}',
            ['as' => 'cashbox.show',
          'uses' => 'Mebius\Controller\CashboxController@show']);
        #####################
        ## Report
        Route::get('report',
            ['as' => 'report.index',
          'uses' => 'Mebius\Controller\ReportController@getIndex']);
        Route::get('report/export',
            ['as' => 'report.export',
          'uses' => 'Mebius\Controller\ReportController@export']);
        #####################
        ## Help
        Route::get('help',
            ['as' => 'help.index',
          'uses' => 'Mebius\Controller\HelpController@getIndex']);
    });
});
Route::post('login', 'Mebius\Controller\AuthController@postLogin');
Route::get('login',
    ['as' => 'login', 'uses' => 'Mebius\Controller\AuthController@showLogin']);

app/models/User.php
<?php

use \Illuminate\Auth\Reminders\RemindableInterface;
use \Illuminate\Auth\Reminders\RemindableTrait;
use \Illuminate\Auth\UserInterface;
use \Illuminate\Auth\UserTrait;
use \Mebius\Model\ValidatableModel;

class User extends ValidatableModel implements UserInterface, RemindableInterface
{

    use UserTrait,
        RemindableTrait;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
      'password',
      'remember_token',
      'api_key',
        //'role_id'
    ];

    /**
     *
     * @var array type
     */
    protected $guarded = ['id'];
    //protected $visible = ['name', 'phone', 'email'];
    protected $fillable = [
      'name',
      'phone',
      'email',
      //'role_id',
      'role',
      'password',
    ];

    /*
     * `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
      `name` VARCHAR(255) NOT NULL COLLATE 'utf8_unicode_ci',
      `password` VARCHAR(255) NOT NULL COLLATE 'utf8_unicode_ci',
      `api_key` VARCHAR(32) NOT NULL COLLATE 'utf8_unicode_ci',
      `phone` VARCHAR(16) NOT NULL COLLATE 'utf8_unicode_ci',
      `email` VARCHAR(100) NOT NULL COLLATE 'utf8_unicode_ci',
      `role_id` TINYINT(3) UNSIGNED NOT NULL,
     */

    /**
     *
     * @var array
     */
    protected static $rules = [
      'name' => ['required', 'regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'between:4,100'],
      'password' => ['alpha_dash', 'between:4,100'],
      'phone' => ['required', 'regex:/^[\d\+\-\(\) ]{11,18}$/ui'],
      'email' => ['required', 'email', 'max:200'],
        //'role_id' => ['required', 'exists:roles,id'],
    ];

    protected static function boot()
    {

        static::creating(function($model) {
            static::$rules['password'][] = 'required';
            static::$rules['email'][] = 'unique:users';
        });

        static::updating(function($model) {
            /* @var $model \Illuminate\Database\Eloquent\Model */
            if (!$model->getAttribute('password')) {
                //$model->original['password'] = '';
                $model->syncOriginalAttribute('password');
            }
            if ($model->getAttribute('email') != $model->getOriginal('email')) {
                static::$rules['email'][] = 'unique:users';
            }
        });


        parent::boot();

        //echo '<pre>', print_r(static::$rules['role_id']), '</pre>';

        /* static::saving(function($model) {
          if ($model->getAttribute('password')) {
          $model->password = Hash::make($model->password);
          }
          }); */
        static::creating(function($model) {
            $model->password = Hash::make($model->password);
            $model->created_by = \Auth::user()->id;
            $model->updated_by = \Auth::user()->id;
        });
        static::updating(function($model) {
            //echo 'firing a after parent::boot updating <br/>';
            /* @var $model ValidatableModel */
            if ($model->getAttribute('password')) {
                $model->password = Hash::make($model->password);
            }
            $model->updated_by = \Auth::user()->id;
        });
    }

    public function role()
    {
        return $this->hasOne('Role', 'id', 'role_id');
    }

    public function roles()
    {
        return $this->belongsToMany('Role');
    }

    public function authAttempts()
    {
        return $this->hasMany('AuthAttempt', 'created_by', 'id');
    }

    public function setPhoneAttribute($phone)
    {
        $this->attributes['phone'] = sanitize_phone($phone);
    }

}

app/views/user/form.blade.php
@extends('includes.extends_master')

{{-- Content --}}
@section('content')

{{ Form::model($user, array('route' => $route, 'class' => 'form-horizontal','role'=>'form','method'=>(isset($method)?$method:'POST'))) }}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{{$page_title}}</h3>
    </div>
    <div class="panel-body">

        <!-- Name -->
        <div class="form-group{{{ $errors->has('name') ? ' has-error' : '' }}}">
            {{ Form::label('name', 'Имя', array('class' => 'col-sm-4 control-label')) }}
            <div class="col-sm-8">
                {{ Form::text('name', Input::old('name'), array('class' => 'form-control')) }}
                <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>
        </div>

        <!-- Email -->
        <div class="form-group{{{ $errors->has('email') ? ' has-error' : '' }}}">
            {{ Form::label('email', 'Email', array('class' => 'col-sm-4 control-label')) }}
            <div class="col-sm-8">
                {{ Form::email('email', Input::old('email'), array('class' => 'form-control')) }}
                <span class="text-danger">{{ $errors->first('email') }}</span>
            </div>
        </div>

        <!-- Phone -->
        <div class="form-group{{{ $errors->has('phone') ? ' has-error' : '' }}}">
            {{ Form::label('phone', 'Телефон', array('class' => 'col-sm-4 control-label')) }}
            <div class="col-sm-8">
                {{ Form::input('tel', 'phone', Input::old('phone'), ['class' => 'form-control bfh-phone','data-format'=>get_phone_format()]) }}
                <span class="text-danger">{{ $errors->first('phone') }}</span>
            </div>
        </div>

        <!-- Role -->
        <div class="form-group">
            <label class="col-sm-4 control-label" for="role_id">Роль</label>
            <div class="col-sm-8">
                <fieldset>
                    <span class="text-danger">{{ $errors->first('role_id') }}</span>
                    @foreach ($roles as $role_id => $role_name)
                    <div class="form-group-sm">
                        {{ Form::checkbox("role_id[]", $role_id, $user->roles->contains($role_id)) }}
                        {{ $role_name }}
                    </div>
                    @endforeach
                </fieldset>
            </div>
        </div>

        <!-- Password -->
        <div class="form-group{{{ $errors->has('password') ? ' has-error' : '' }}}">
            {{ Form::label('password', 'Пароль', array('class' => 'col-sm-4 control-label')) }}
            <div class="col-sm-8">
                {{ Form::text('password', '', array('class' => 'form-control')) }}
                <span class="text-danger">{{ $errors->first('password') }}</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                {{ Form::submit('Сохранить', array('class' => 'btn btn-large btn-primary')) }}
            </div>
        </div>
    </div>
</div>

{{ Form::close() }}

{{ HTML::script('/js/bootstrap-formhelpers-phone.js') }}

@stop

app/views/user/index.blade.php
@extends('includes.extends_master')

{{-- Content --}}
@section('content')

@if(route_allowed('user.create'))
<div class="row">
    <a class="btn btn-large btn-primary col-sm-4" href="<?=
    URL::route('user.create', null, false)

    ?>">
        Добавить нового пользователя
    </a>
</div>
@endif

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">Список пользователей</div>

    <div class="list-group">
        @foreach ($users as $user)
        <a href="{{URL::route('user.show', $user->id, false)}}" class="list-group-item<?=
        $user->id == \Auth::user()->id ? ' active' : ''

        ?>">
            <h4 class="list-group-item-heading">{{{$user->name}}}</h4>
            @foreach($user->roles as $role)
            <p class="list-group-item-text text-primary"><i>{{{$role->name}}}</i></p>
            @endforeach
            <p class="list-group-item-text">{{{$user->phone}}}</p>
            <p class="list-group-item-text">{{{$user->email}}}</p>
        </a>
        @endforeach
    </div>
</div>

<?php /*
  foreach ($users as $key => $user) {
  echo $user->name . ' (' . $user->role->name . ')<br/>';
  echo '<a href="' . URL::route('user.edit', ['id' => $user['id']], false) . '">Править</a> '
  . '| <a href="' . URL::route('user.destroy', ['id' => $user['id']], false) . '">Удалить</a><br/>';
  echo ' <hr/>';
  }

 */ ?>
@stop

app/views/user/show.blade.php
@extends('includes.extends_master')

{{-- Content --}}
@section('content')
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Пользователь</h3>
    </div>
    <div class="panel-body">
        <dl>
            <dt>{{{$user->name}}}</dt>
            <dd>
                @foreach($user->roles as $role)
                <p class="list-group-item-text text-primary"><i>{{{$role->name}}}</i></p>
                @endforeach
            </dd>
            <dd>{{{$user->phone}}}</dd>
            <dd>{{{$user->email}}}</dd>
            <dd>{{$user->{\User::CREATED_AT};}}</dd>
        </dl>
        @include('includes.control_unit',[
        'edit_route' => 'user.edit',
        'delete_route' => 'user.destroy',
        'model' => $user,
        ])
    </div>
</div>
@stop