app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

Route::filter('ACL', 'Mebius\Filter\AclPermittedFilter');

Route::when('*', 'csrf', ['post', 'put', 'delete']);

Route::group(['before' => 'auth'],
    function () {
    Route::get('/',
        ['as' => 'main',
      'uses' => 'Mebius\Controller\MainController@indexAction'
    ]);
    Route::get('logout',
        ['as' => 'logout',
      'uses' => 'Mebius\Controller\AuthController@getLogout']);
    Route::put('auth/settings',
        ['as' => 'auth.settings.put',
      'uses' => 'Mebius\Controller\AuthController@putSettings']);
    Route::get('auth/settings',
        ['as' => 'auth.settings.get',
      'uses' => 'Mebius\Controller\AuthController@getSettings']);
    #####################
    ## ACL
    Route::group(['before' => 'ACL'],
        function () {
        #####################
        ## Entry
        Route::match(['GET', 'POST'], 'entry/search',
            ['as' => 'entry.search',
          'uses' => 'Mebius\Controller\EntryController@search']);
        Route::put('entry/{entry}/status',
            ['as' => 'entry.status',
          'uses' => 'Mebius\Controller\EntryController@status']);
        Route::get('entry/export',
            ['as' => 'entry.export',
          'uses' => 'Mebius\Controller\EntryController@export']);
        Route::get('entry/{entry}/showlogs',
            ['as' => 'entry.showlogs',
          'uses' => 'Mebius\Controller\EntryController@showlogs']);
        Route::resource('entry', 'Mebius\Controller\EntryController');
        ###############
        ## Order
        Route::match(['GET', 'POST'], 'order/search',
            ['as' => 'order.search',
          'uses' => 'Mebius\Controller\OrderController@search']);
        Route::get('order/export',
            ['as' => 'order.export',
          'uses' => 'Mebius\Controller\OrderController@export']);
        Route::post('order/{order}/finish',
            ['as' => 'order.finish',
          'uses' => 'Mebius\Controller\OrderController@finish']);
        Route::get('order/{order}/status/{status}',
            ['as' => 'order.status.get',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::put('order/{order}/status/{status}',
            ['as' => 'order.status.put',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::get('order/{order}/showlogs',
            ['as' => 'order.showlogs',
          'uses' => 'Mebius\Controller\OrderController@showlogs']);
        Route::post('order/{order}/cancel',
            ['as' => 'order.cancel',
          'uses' => 'Mebius\Controller\OrderController@cancel']);
        Route::post('order/{order}/archivate',
            ['as' => 'order.archivate',
          'uses' => 'Mebius\Controller\OrderController@archivate']);
        Route::post('order/{order}/stuff',
            ['as' => 'order.stuff',
          'uses' => 'Mebius\Controller\OrderController@stuff']);
        // Добавление денег в кассу
        Route::post('order/{order}/cashbox',
            ['as' => 'order.cashbox',
          'uses' => 'Mebius\Controller\OrderController@cashbox']);
        Route::resource('order', 'Mebius\Controller\OrderController');
        #####################
        ## User
        Route::resource('user', 'Mebius\Controller\UserController');
        #####################
        ## Role
        Route::resource('role', 'Mebius\Controller\RoleController');
        #####################
        ## Refer
        Route::resource('refer', 'Mebius\Controller\ReferController');
        #####################
        ## Cashbox
        Route::get('cashbox',
            ['as' => 'cashbox.index',
          'uses' => 'Mebius\Controller\CashboxController@getIndex']);
        Route::get('cashbox/export',
            ['as' => 'cashbox.export',
          'uses' => 'Mebius\Controller\CashboxController@export']);
        Route::get('cashbox/{order}',
            ['as' => 'cashbox.show',
          'uses' => 'Mebius\Controller\CashboxController@show']);
        #####################
        ## Report
        Route::get('report',
            ['as' => 'report.index',
          'uses' => 'Mebius\Controller\ReportController@getIndex']);
        Route::get('report/export',
            ['as' => 'report.export',
          'uses' => 'Mebius\Controller\ReportController@export']);
        #####################
        ## Help
        Route::get('help',
            ['as' => 'help.index',
          'uses' => 'Mebius\Controller\HelpController@getIndex']);
    });
});
Route::post('login', 'Mebius\Controller\AuthController@postLogin');
Route::get('login',
    ['as' => 'login', 'uses' => 'Mebius\Controller\AuthController@showLogin']);

app/models/Entry.php
<?php

use Mebius\Model\Contracts\EntryInterface;
use Mebius\Model\OptionedModel;

class Entry extends OptionedModel implements EntryInterface
{

    protected $table = 'entries';

    /**
     *
     */
    const ORDER_KEY = 'order_key';
    const VISIT_TIME = 'visit_time';
    const DEFER_BEFORE = 'defer_before';

    /**
     *
     */
    const TYPE_DATE = 'date';
    const TYPE_STRING = 'string';

    /**
     * Statuses
     */
    const STATUS_ACTIVE = 'ACTIVE';
    const STATUS_DEFERRED = 'DEFERRED';
    const STATUS_REFUSED = 'REFUSED';
    const STATUS_ARCHIVED = 'ARCHIVED';

    /**
     * The attributes that should be hidden for arrays.
     * @var array
     */
    protected $hidden = [
      'user_id',
      'supplier_id',
      'refer_id',
      'created_by',
      'updated_by',
    ];

    /**
     *
     */
    protected $nameKey = 'order_key';

    /**
     *
     * @var array
     */
    protected $guarded = ['order_created'];

    /**
     *
     * @var array
     */
    /* protected $dates = [
      'visit_time',
      'view_time',
      'call_time'
      ]; */


    protected $isLoggable = true;
    protected $noLogFields = [
      'finish_time',
      'updated_by',
      'defer_time',
    ];
    protected $logCallbacks = [
      'visit_time' => 'human_date_time',
      'call_time' => 'human_date_time',
      'defer_time' => 'human_date_time',
      'view_time' => 'human_date_time',
      'refuse_time' => 'human_date_time',
      'defer_before' => 'human_date',
    ];
    protected $relationsKeys = [
      'user_id' => 'master',
      'refer_id' => 'refer',
      'supplier_id' => 'supplier',
    ];

    /**
     *
     * @var array
     */
    protected $fillable = [
      'title',
      'client_name',
      'client_phone',
      'metro',
      'mo_town',
      'descr',
      'user_id',
      'supplier_id',
      'refer_id',
      'visit_time',
      'details',
      'refuse_reason',
      'defer_before',
      'defer_reason',
    ];

    /**
     *
     * @var array
     */
    protected static $rules = [
      'title' => ['required', 'regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:100'],
      'client_name' => ['required', 'regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:200'],
      'client_phone' => ['required', 'regex:/^[\d\+\-\(\) ]{11,18}$/ui'],
      'metro' => ['regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:40'],
      'mo_town' => ['regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:50'],
      'descr' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      //'user_id' => ['sometimes', 'exists:users,id'],
      'supplier_id' => ['numeric', 'exists:users,id'],
      'refer_id' => ['numeric', 'exists:refers,id'],
      //'view_time' => ['date'],
      //'call_time' => ['date'],
      'visit_time' => ['date'],
      //'refuse_time' => ['date'],
      'details' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      'refuse_reason' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000', 'required_if:status,REFUSED'],
      'defer_reason' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000', 'required_if:status,DEFERRED'],
      'defer_before' => ['required_if:status,DEFERRED', 'date'],
    ];

    /**
     * Поля сокращенной выборки
     * @var array
     */
    protected $shortStatement = [
      'order_key',
      'title',
      'client_name',
      'client_phone',
      'metro',
      'mo_town',
      'descr',
      'user_id',
      'supplier_id',
      'refer_id',
      'view_time',
      'visit_time',
      'details',
      'status',
      'defer_time',
      'defer_before',
      'defer_reason',
      'refuse_time',
      'refuse_reason',
      'created_at',
      'created_by',
    ];

    protected static function boot()
    {
        static::updating(function($entry) {
            //static::$rules['visit_time'][] = 'after:' . date('d-m-Y');
            if (strtotime($entry->defer_before) <= 0) {
                unset($entry->defer_before);
            }
        });

        parent::boot();

        static::creating(function($entry) {
            $entry->order_key = static::makeOrderKey();
            $entry->created_by = Auth::user()->id;
            $entry->updated_by = Auth::user()->id;
        });

        static::updating(function($entry) {
            $entry->updated_by = Auth::user()->id;
        });
    }

    public function master()
    {
        return $this->hasOne('User', 'id', 'user_id');
    }

    public function supplier()
    {
        return $this->hasOne('User', 'id', 'supplier_id');
    }

    public function operator()
    {
        return $this->hasOne('User', 'id', 'created_by');
    }

    public function updater()
    {
        return $this->hasOne('User', 'id', 'updated_by');
    }

    public function refer()
    {
        return $this->hasOne('Refer', 'id', 'refer_id');
    }

    public static function makeOrderKey()
    {
        //return date("dmy-") . (self::whereRaw('DATE(' . static::CREATED_AT . ') = ?',
        //array(date("Y-m-d")))->count() + 1);
        $dp = date("dmy-");
        $res = self::whereRaw('DATE(' . static::CREATED_AT . ') = ?',
                [date("Y-m-d")])->orderBy('id', 'DESC')->first([static::ORDER_KEY]);
        /* , strtotime('tomorrow') */
        if ($res) {
            $dp .= (explode($dp, $res->{static::ORDER_KEY})[1] + 1);
        } else {
            $dp .= '1';
        }
        $dp = "M-{$dp}";
        //die($dp);
        return $dp;
    }

    public function setOrderCreated($bool = true)
    {
        $this->attributes['order_created'] = (int) $bool;
    }

    public function setCallTime($timestamp = false)
    {
        if ($timestamp === false) {
            $timestamp = time();
        }
        if ($this->exists && !$this->is_called) {
            $this->call_time = date(static::getDateTimeFormat(), $timestamp);
        }
    }

    public function setArchivedAt($timestamp = false)
    {
        if ($timestamp === false) {
            $timestamp = time();
        }
        if ($this->exists) {
            $this->archived_at = date(static::getDateTimeFormat(), $timestamp);
        }
    }

    public function setStatus($status)
    {
        if ($this->exists) {
            switch ($status) {
                case 'refuse':
                    $this->status = self::STATUS_REFUSED;
                    break;
                case 'defer':
                    $this->status = self::STATUS_DEFERRED;
                    break;
                case 'active':
                    $this->status = self::STATUS_ACTIVE;
                    break;
                case 'archive':
                    $this->status = self::STATUS_ARCHIVED;
                    $this->setArchivedAt();
                    break;
                default:
                    break;
            }
        }
    }

    public function setRefuseTime($timestamp = false)
    {
        if ($this->exists) {
            if (!$this->is_refused) {
                if ($timestamp === false) {
                    $timestamp = time();
                }
                $this->refuse_time = date(static::getDateTimeFormat(),
                    $timestamp);
            } elseif ($timestamp === 0) {
                $this->refuse_time = static::getDefaultDateTimeString();
            }
        }
    }

    public function setDeferTime($timestamp = false)
    {
        if ($this->exists) {
            if (!$this->is_defered) {
                if ($timestamp === false) {
                    $timestamp = time();
                }
                $this->defer_time = date(static::getDateTimeFormat(), $timestamp);
            } elseif ($timestamp === 0) {
                $this->defer_time = static::getDefaultDateTimeString();
            }
        }
    }

    public function unsetEmptyDates()
    {
        if ($this->exists) {
            if (strtotime($this->visit_time) <= 0) {
                unset($this->visit_time);
            }
            if (strtotime($this->call_time) <= 0) {
                unset($this->call_time);
            }
        }
    }

    /**
     * Удаляет из текущего объекта даты выезда и звонка
     * чтоб не было конфликтов правил при сохранении
     */
    public function unsetMasterDates()
    {
        if ($this->exists) {
            unset($this->visit_time);
            unset($this->call_time);
        }
    }

    public function getIsNewAttribute()
    {
        if ($this->exists) {
            return (strtotime($this->view_time) <= 0);
        }
        return true;
    }

    public function getIsCallWaitAttribute()
    {
        if ($this->exists) {
            return (!$this->is_new && !$this->is_called);
        }
    }

    public function getIsCalledAttribute()
    {
        if ($this->exists) {
            return (strtotime($this->call_time) > 0);
        }
    }

    public function getIsVisitWaitAttribute()
    {
        if ($this->exists) {
            $visit_time = strtotime($this->visit_time);
            return date('Ymd', $visit_time) >= date('Ymd');
            //return strtotime($this->visit_time) > time();
        }
    }

    public function getIsVisitTimeWaitAttribute()
    {
        if ($this->exists) {
            return strtotime($this->visit_time) <= 0 && strtotime($this->call_time) > 0;
        }
    }

    public function getVisitTimeIssetAttribute()
    {
        if ($this->exists) {
            return strtotime($this->visit_time) > 0;
        }
    }

    public function getMasterIssetAttribute()
    {
        if ($this->exists) {
            return !is_null($this->master);
        }
    }

    public function getIsOverdueAttribute()
    {
        if ($this->exists) {
            $visit_time = strtotime($this->visit_time);
            return ($visit_time > 0 && date('Ymd', $visit_time) < date('Ymd'));
        }
    }

    public function getIsRefusedAttribute()
    {
        if ($this->exists) {
            //return (strtotime($this->refuse_time) > 0);
            return $this->attributes['status'] == static::STATUS_REFUSED;
        }
    }

app/views/entry/__show.blade.php
@extends('includes.extends_master')

{{-- Content --}}
@section('content')

<?php
//echo '<pre>', print_r($entry->toArray()), '</pre>';
//die();

$view_time = \strtotime($entry->view_time);
$call_time = \strtotime($entry->call_time);
$visit_time = \strtotime($entry->visit_time);
$refuse_time = \strtotime($entry->refuse_time);
$owner = (!is_null($entry->master) && \Auth::id() == $entry->master->id);


/* @var $errors Illuminate\Support\ViewErrorBag */
//echo '<pre>', print_r($errors), '</pre>';

?>

@if($errors->count())
<div class="alert alert-danger alert-block">
    На странице имеются ошибки: {{{ $errors->first() }}}
</div>
@endif

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="glyphicon glyphicon-{{ $entry->getIcon() }}"></span>
            {{{ $entry->order_key }}} /
            {{{ is_null($entry->master)? 'без мастера' : $entry->master->name }}}
        </h3>
    </div>
    <div class="panel-body">

        {{ Form::model($entry, array(
                    'url' => $route,
                    'class' => 'form-horizontal',
                    'role'=>'form',
                    'method'=>(isset($method)?$method:'POST'))) }}

        <div class="form-group">
            <label class="col-sm-4 control-label">Дата</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    {{{date('j.m.Y в H:i',strtotime($entry->created_at))}}}
                </p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Заголовок</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->title}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Имя</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->client_name}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Телефон</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    <a class="btn btn-success" href="tel:{{{ $entry->client_phone }}}">
                        <span class="glyphicon glyphicon-earphone"> </span>
                        <span class="bfh-phone" data-format="<?= get_phone_format() ?>" data-number="{{$entry->client_phone}}"></span>
                    </a>
                </p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Метро</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->metro}}}</p>
            </div>
        </div>

        @if(!empty($entry->mo_town))
        <div class="form-group">
            <label class="col-sm-4 control-label">М.О.</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->mo_town}}}</p>
            </div>
        </div>
        @endif

        <div class="form-group">
            <label class="col-sm-4 control-label">Описание</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{\nl2br($entry->descr)}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Источник</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->refer->name}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Мастер</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    @if(is_null($entry->master))
                    не назначен
                    @else
                    <a class="btn btn-success" href="tel:{{{ $entry->master->phone }}}">
                        <span class="glyphicon glyphicon-earphone"> </span>
                        <span>{{ $entry->master->name }}</span>
                    </a>
                    @endif
                </p>
            </div>
        </div>

        @if(!is_null($entry->master))
        <div class="form-group">
            <label class="col-sm-4 control-label">Просмотрена</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    @if($view_time > 0)
                    {{\date('j.m.Y в H:i',$view_time);}}
                    @else
                    Нет
                    @endif
                </p>
            </div>
        </div>
        @endif

        @if($call_time > 0)
        <div class="form-group">
            <label class="col-sm-4 control-label">Звонок</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    {{\date('j.m.Y в H:i',$call_time);}}
                </p>
            </div>
        </div>
        @endif

        @if($entry->is_deferred)
        <div class="form-group">
            <label class="col-sm-4 control-label">Отложена до</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    {{\date('j.m.Y',\strtotime($entry->defer_before));}}
                </p>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label">Причина</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    {{ $entry->defer_reason }}
                </p>
            </div>
        </div>
        @endif

        @if($refuse_time > 0)
        <div class="form-group">
            <label class="col-sm-4 control-label">Отказ</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    {{\date('j.m.Y в H:i',$refuse_time);}}
                </p>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label">Причина отказа</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    @if(!empty($entry->refuse_reason))
                    {{\nl2br($entry->refuse_reason)}}
                    @else
                    <i>Не указана</i>
                    @endif
                </p>
            </div>
        </div>

        @endif

        @include('entry.inc.visit_time_form')

        {{ Form::close() }}

        <div class="btn-group">

            @if(isset($routes['reanimate']))
            {{ Form::postButton($routes['reanimate'],
                "Восстановить ".(isset($reanimate_msg)?$reanimate_msg:$entry->order_key)."?") }}
            @endif

            @if(isset($routes['archiving']))
            {{ Form::postButton($routes['archiving'],
                "Переместить в архив ".(isset($reanimate_msg)?$reanimate_msg:$entry->order_key)."?") }}
            @endif

            @if(isset($routes['edit']))
            <a class="btn btn-primary btn-sm" href="{{$routes['edit']['route']}}">{{$routes['edit']['name']}}</a>
            @endif

            @if(isset($routes['delete']))
            {{ Form::btnDelete($routes['delete']['route'],"Удалить заявку №".$entry->order_key." безвозвратно?") }}
            @endif

            @if(isset($routes['showlogs']))
            @include('includes.showlogs',['route' => $routes['showlogs']])
            @endif

        </div>

    </div>
</div>

{{ HTML::script('/js/bootstrap-formhelpers-phone.js') }}


@stop

app/views/entry/master_view.blade.php
@extends('includes.extends_master')

{{-- Content --}}
@section('content')

<?php
$view_time = strtotime($entry->view_time);
$call_time = strtotime($entry->call_time);
$visit_time = strtotime($entry->visit_time);
$owner = \Auth::id() == $entry->master->id;

?>


<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            {{{ $page_title}}}
            @if($view_time <= 0)
            <span class="label label-default pull-right">Новая</span>
            @endif
        </h3>
    </div>
    <div class="panel-body">

        {{ Form::model($entry, array(
                    'route' => $route,
                    'class' => 'form-horizontal',
                    'role'=>'form',
                    'method'=>(isset($method)?$method:'POST'))) }}

        <div class="form-group">
            <label class="col-sm-4 control-label">Дата</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    {{{date('j.m.Y в H:i',strtotime($entry->created_at))}}}
                </p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Заголовок</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->title}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Метро</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->metro}}}</p>
            </div>
        </div>

        @if(!empty($entry->mo_town))
        <div class="form-group">
            <label class="col-sm-4 control-label">М.О.</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->mo_town}}}</p>
            </div>
        </div>
        @endif

        <div class="form-group">
            <label class="col-sm-4 control-label">Телефон</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->client_phone}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Имя</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->client_name}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Детали</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->descr}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Мастер</label>
            <div class="col-sm-8">
                <p class="form-control-static">{{{$entry->master->name}}}</p>
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-4 control-label">Просмотрена</label>
            <div class="col-sm-8">
                <p class="form-control-static">
                    @if($view_time > 0)
                    {{date('j.m.Y в H:i',$view_time);}}
                    @else
                    Нет
                    @endif
                </p>
            </div>
        </div>

        @if($view_time > 0)
        @include('entry.inc.visit_time_form')
        @endif

        {{ Form::close() }}

        @include('includes.control_unit',[
        'edit_route' => 'entry.edit',
        'delete_route' => 'entry.destroy',
        'delete_msg' => 'заявку №'.$entry->order_key,
        'model' => $entry,
        ])

    </div>
</div>




@stop

app/views/entry/search.blade.php
@extends('includes.extends_master')

{{-- Content --}}
@section('content')

    {{ HTML::style('/css/datepicker3.css') }}
    {{ HTML::script('/js/bootstrap-datepicker.js') }}
    {{ HTML::script('/js/bootstrap-datepicker.ru.js') }}
    {{ HTML::style('/css/typeahead.css') }}
    {{ HTML::script('/js/typeahead.bundle.min.js') }}
    {{ HTML::script('/js/jquery.inputmask.js') }}

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <div class="row">
                {{Form::open()}}
                <div class="col-md-2">

                    <select name="search_by" id="search_by" class="form-control" onChange="">
                        @foreach($options as $key => $val)
                            <option value="{{$key}}"
                                    <?=
                                    isset($input["search_by"]) && $input["search_by"] == $key ? ' selected="selected"'
                                        : '';

                                    ?>
                                    data-type="{{$val['type']}}">{{$val['name']}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="col-md-4">
                    {{ Form::text('search_val', $input["search_val"],
                        array('class' => 'form-control','id'=>'search_val')) }}
                </div>

                <div class="col-md-3">
                    {{Form::button("Искать", array(
                        'type' => 'submit',
                        'name' => 'doSearch',
                        'class' => 'btn btn-info btn col-xs-12'
                        )) }}

                </div>
                {{ Form::close() }}
            </div>
        </div>

        <?php /* @var $entries Illuminate\Database\Eloquent\Collection */ ?>

        @if(!$entries->count())
            <div class="panel-body">
                <p>Ничего не найдено по данному запросу.</p>
            </div>
        @else
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>№</th>
                    <th>Заголовок</th>
                    <th>Мастер</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($entries as $entry)
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-{{ $entry->getIcon() }}"></span>
                            <a href="{{ $entry->url }}">{{{$entry->order_key}}}</a>
                        </td>
                        <td>{{{$entry->title}}}</td>
                        <td>@if($entry->master_isset){{{$entry->master->name}}}@else - не назначен - @endif</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @endif
    </div>

    <div class="well">
        @foreach($icons as $key => $val)
            <span class="glyphicon glyphicon-{{ $val }}"></span> - {{ trans('status.' . strtolower($key)) }}<br/>
        @endforeach
    </div>

    <script>
        $(document).ready(function () {

            metro = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                limit: 10,
                prefetch: '/assets/metro.obj.json'
            });
            metro.initialize();

            set_search_value_class();

            $("#search_by").change(function () {
                $('#search_val').val('');
                $('#search_val').datepicker('remove');
                $('#search_val').typeahead('destroy');
                $('#search_val').inputmask("remove");
                set_search_value_class();
            });
        });

        function set_search_value_class() {
            var type = $("#search_by").find(':selected').data('type');
            if (type === 'date') {
                $('#search_val').datepicker({
                    format: "dd.mm.yyyy",
                    todayBtn: "linked",
                    language: "ru",
                    autoclose: true
                });
            } else if (type === 'metro') {
                $('#search_val').typeahead(null, {
                    name: 'metro',
                    displayKey: 'name',
                    source: metro.ttAdapter()
                });
            } else if (type === 'phone') {
                $('#search_val').inputmask('<?= get_phone_format('9') ?>');
            } else if (type === 'order_key') {
                $('#search_val').inputmask({mask: "M-999999-9[9][9]", greedy: false});
            } else {
                //$('#search_val').val('');
            }

            //alert($("#search_val").attr('class'));
        }
    </script>

@stop