app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

Route::filter('ACL', 'Mebius\Filter\AclPermittedFilter');

Route::when('*', 'csrf', ['post', 'put', 'delete']);

Route::group(['before' => 'auth'],
    function () {
    Route::get('/',
        ['as' => 'main',
      'uses' => 'Mebius\Controller\MainController@indexAction'
    ]);
    Route::get('logout',
        ['as' => 'logout',
      'uses' => 'Mebius\Controller\AuthController@getLogout']);
    Route::put('auth/settings',
        ['as' => 'auth.settings.put',
      'uses' => 'Mebius\Controller\AuthController@putSettings']);
    Route::get('auth/settings',
        ['as' => 'auth.settings.get',
      'uses' => 'Mebius\Controller\AuthController@getSettings']);
    #####################
    ## ACL
    Route::group(['before' => 'ACL'],
        function () {
        #####################
        ## Entry
        Route::match(['GET', 'POST'], 'entry/search',
            ['as' => 'entry.search',
          'uses' => 'Mebius\Controller\EntryController@search']);
        Route::put('entry/{entry}/status',
            ['as' => 'entry.status',
          'uses' => 'Mebius\Controller\EntryController@status']);
        Route::get('entry/export',
            ['as' => 'entry.export',
          'uses' => 'Mebius\Controller\EntryController@export']);
        Route::get('entry/{entry}/showlogs',
            ['as' => 'entry.showlogs',
          'uses' => 'Mebius\Controller\EntryController@showlogs']);
        Route::resource('entry', 'Mebius\Controller\EntryController');
        ###############
        ## Order
        Route::match(['GET', 'POST'], 'order/search',
            ['as' => 'order.search',
          'uses' => 'Mebius\Controller\OrderController@search']);
        Route::get('order/export',
            ['as' => 'order.export',
          'uses' => 'Mebius\Controller\OrderController@export']);
        Route::post('order/{order}/finish',
            ['as' => 'order.finish',
          'uses' => 'Mebius\Controller\OrderController@finish']);
        Route::get('order/{order}/status/{status}',
            ['as' => 'order.status.get',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::put('order/{order}/status/{status}',
            ['as' => 'order.status.put',
          'uses' => 'Mebius\Controller\OrderController@status']);
        Route::get('order/{order}/showlogs',
            ['as' => 'order.showlogs',
          'uses' => 'Mebius\Controller\OrderController@showlogs']);
        Route::post('order/{order}/cancel',
            ['as' => 'order.cancel',
          'uses' => 'Mebius\Controller\OrderController@cancel']);
        Route::post('order/{order}/archivate',
            ['as' => 'order.archivate',
          'uses' => 'Mebius\Controller\OrderController@archivate']);
        Route::post('order/{order}/stuff',
            ['as' => 'order.stuff',
          'uses' => 'Mebius\Controller\OrderController@stuff']);
        // Добавление денег в кассу
        Route::post('order/{order}/cashbox',
            ['as' => 'order.cashbox',
          'uses' => 'Mebius\Controller\OrderController@cashbox']);
        Route::resource('order', 'Mebius\Controller\OrderController');
        #####################
        ## User
        Route::resource('user', 'Mebius\Controller\UserController');
        #####################
        ## Role
        Route::resource('role', 'Mebius\Controller\RoleController');
        #####################
        ## Refer
        Route::resource('refer', 'Mebius\Controller\ReferController');
        #####################
        ## Cashbox
        Route::get('cashbox',
            ['as' => 'cashbox.index',
          'uses' => 'Mebius\Controller\CashboxController@getIndex']);
        Route::get('cashbox/export',
            ['as' => 'cashbox.export',
          'uses' => 'Mebius\Controller\CashboxController@export']);
        Route::get('cashbox/{order}',
            ['as' => 'cashbox.show',
          'uses' => 'Mebius\Controller\CashboxController@show']);
        #####################
        ## Report
        Route::get('report',
            ['as' => 'report.index',
          'uses' => 'Mebius\Controller\ReportController@getIndex']);
        Route::get('report/export',
            ['as' => 'report.export',
          'uses' => 'Mebius\Controller\ReportController@export']);
        #####################
        ## Help
        Route::get('help',
            ['as' => 'help.index',
          'uses' => 'Mebius\Controller\HelpController@getIndex']);
    });
});
Route::post('login', 'Mebius\Controller\AuthController@postLogin');
Route::get('login',
    ['as' => 'login', 'uses' => 'Mebius\Controller\AuthController@showLogin']);

app/models/Order.php
<?php

use Illuminate\Database\Eloquent\Relations\HasMany;
use Mebius\Model\Contracts\OrderInterface;
use Mebius\Model\OptionedModel;

class Order extends OptionedModel implements OrderInterface
{

    protected $table = 'orders';
    protected $primaryKey = 'order_key';

    /**
     *
     */
    const ORDER_KEY = 'order_key';
    const FINISH_DATE = 'finish_date';
    const FINISHED_TIME = 'finished_time';
    const ARCHIVED_AT = 'archived_at';

    /**
     *
     */
    const STATUS_ACTIVE = 'CREATED';
    const STATUS_FINISHED = 'FINISHED';
    const STATUS_ARCHIVED = 'ARCHIVED';

    /**
     *
     */
    const TYPE_DATE = 'date';
    const TYPE_STRING = 'string';
    const TYPE_PHONE = 'phone';

    /* protected $STATUSES = [
      'FINISHED' => 'FINISHED',
      ]; */

    protected $isLoggable = true;
    protected $noLogFields = [
      Order::FINISHED_TIME,
      'updated_by',
    ];
    protected $relationsKeys = [
      'user_id' => 'master',
      'refer_id' => 'refer',
      'supplier_id' => 'supplier',
    ];

    /**
     * The attributes that should be hidden for arrays.
     * @var array
     */
    protected $hidden = [
      'refer_id',
      'created_by',
      'updated_by',
    ];

    /**
     *
     * @var array
     */
    protected $guarded = [];

    /**
     *
     * @var array
     */
    protected $fillable = [
      'order_key',
      'title',
      'client_name',
      'client_phone',
      'metro',
      'mo_town',
      'descr',
      'details',
      'supplier_id',
      'refer_id',
      'cashless',
      'inplace',
      'cost',
      'prepay',
      'result_amount',
      'cashbox',
      'comment',
      'docs_signed',
      Order::FINISH_DATE,
      'created_by', // чтоб можно было мастера менять
    ];

    /* Array

      [photo] => Array
      (
      [0] =>
      )

      ) */

    /**
     *
     * @var array
     */
    protected static $rules = [
      'order_key' => ['required', 'regex:/^\w\-\d{5,6}\-\d+$/ui'],
      'title' => ['required', 'regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:100'],
      'client_name' => ['required', 'regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:200'],
      'client_phone' => ['required', 'regex:/^[\d\+\-\(\) ]{11,18}$/ui'],
      'metro' => ['regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:40'],
      'mo_town' => ['regex:/^[\pL\pZ\pS\pN\pP]+$/ui', 'max:50'],
      'descr' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      'details' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      'supplier_id' => ['numeric', 'exists:users,id'],
      'refer_id' => ['numeric', 'exists:refers,id'],
      'cashless' => ['integer', 'in:0,1'],
      'inplace' => ['integer', 'in:0,1'],
      'docs_signed' => ['integer', 'in:0,1'],
      'cost' => ['required', 'numeric'],
      'prepay' => ['numeric'],
      'cashbox' => ['numeric'],
      'result_amount' => ['numeric'],
      'comment' => ['regex:/[\pL\pZ\pS\pN\pP]+/ui', 'max:65000'],
      Order::FINISH_DATE => ['required', 'date'],
    ];

    /**
     * Поля сокращенной выборки
     * @var array
     */
    protected $shortStatement = [
      'order_key',
      'title',
      'client_name',
      'client_phone',
      'metro',
      'mo_town',
      'descr',
      'details',
      'supplier_id',
      'refer_id',
      'cashless',
      'inplace',
      'cost',
      'prepay',
      'result_amount',
      'cashbox',
      'comment',
      'docs_signed',
      Order::FINISH_DATE,
      'status',
      'created_by',
    ];

    protected static function boot()
    {
        static::creating(function($order) {
            static::$rules['order_key'][] = 'unique:orders';
        });

        static::updating(function($order) {

        });

        parent::boot();

        static::creating(function($order) {
            //echo '<pre>', print_r($order->toArray()), '</pre>';
            //die();
            $order->created_by = Auth::user()->id;
            $order->updated_by = Auth::user()->id;
        });

        static::updating(function($order) {
            $order->updated_by = Auth::user()->id;
        });
    }

    public function master()
    {
        return $this->hasOne('User', 'id', 'created_by');
    }

    public function supplier()
    {
        return $this->hasOne('User', 'id', 'supplier_id');
    }

    public function operator()
    {
        return $this->hasOne('User', 'id', 'operator_id');
    }

    public function updater()
    {
        return $this->hasOne('User', 'id', 'updated_by');
    }

    public function refer()
    {
        return $this->hasOne('Refer', 'id', 'refer_id');
    }

    /**
     *
     * @return HasMany
     */
    public function stuff()
    {
        return $this->hasMany('Stuff', 'order_id', 'id');
    }

    public function payments()
    {
        return $this->hasMany('Payment', 'order_id', 'id');
    }

    public function setMasterId($id)
    {
        $this->attributes['created_by'] = $id;
    }

    public function setClientPhoneAttribute($phone)
    {
        $this->attributes['client_phone'] = sanitize_phone($phone);
    }

    public function setDescrAttribute($descr)
    {
        //echo '<h1>SETTED</h1>';
        $this->attributes['descr'] = trim($descr);
    }

    public function getIsFinishedAttribute()
    {
        return isset($this->attributes['finished_time']) && strtotime($this->attributes['finished_time']) > 0;
    }

    public function getIsCanceledAttribute()
    {
        return isset($this->attributes['canceled_at']) ? !is_null($this->attributes['canceled_at'])
                : null;
    }

    public function getIsArchivedAttribute()
    {
        return $this->attributes['status'] == self::STATUS_ARCHIVED;
    }

    public function getIsActiveAttribute()
    {
        return $this->attributes['status'] == self::STATUS_ACTIVE;
    }

    public function getMasterIssetAttribute()
    {
        if ($this->exists) {
            return !is_null($this->master);
        }
    }

    public function getMasterNameAttribute()
    {
        if ($this->master_isset) {
            return $this->master->name;
        }
    }

    public function getIsOverdueAttribute()
    {
        return $this->is_active && date('Ymd',
                strtotime($this->getAttribute(Order::FINISH_DATE))) < date('Ymd');
    }

    public function getOrderKeyPrintAttribute()
    {
        return preg_replace('/(\d\d\d\d)(\d\d)(\-)(\d+)/',
            "<b>$1</b>$2$3<b>$4</b>", $this->order_key);
    }

    public function getCanBeClosedAttribute()
    {
        return $this->is_finished;
    }

    /**
     * Добавление суммы в кассу
     * @param int $int добавляемая сумма в кассу
     */
    public function addToCashBox($int)
    {
        $this->attributes['cashbox'] += $int;
    }

    /**
     *
     * @param int $timestamp
     */
    public function setArchivedAt($timestamp = false)
    {
        if ($timestamp === false) {
            $timestamp = time();
        }
        if ($this->exists) {
            $this->archived_at = date(static::getDateTimeFormat(), $timestamp);
        }
    }

    /**
     * Вычисляемое значение района заказа
     * @return int
     */
    public function getLocationAttribute()
    {
        $loc = '';
        if ($this->metro) {
            $loc .= 'м.' . $this->metro . ' ';
        }
        if ($this->mo_town) {
            $loc .= 'г.' . $this->mo_town;
        }
        if (!$loc) {
            $loc = '-';
        }
        return $loc;
    }

    /**
     * Вычисляемое значение долга мастера в кассу
     * (полученные, но не сданные деньги)
     * @return int
     */
    public function getCashboxMasterDebtAttribute()
    {
        return $this->prepay + $this->result_amount - $this->cashbox;
    }

    /**
     * Вычисляемое значение долга в кассу
     * @return int
     */
    public function getCashboxDebtAttribute()
    {
        //echo 'getCashboxDebtAttribute ' . ($this->cost - $this->cashbox);
        return $this->cost - $this->cashbox;
    }

    /**
     * Имеется-ли долг в кассу
     * @return boolean
     */
    public function getHasCashboxDebtAttribute()
    {
        return $this->cashbox_debt > 0;
    }

    /**
     * Вычисляемое значение долга клиента
     * @return int
     */
    public function getDebtAttribute()
    {
        return $this->cashbox_debt;
    }

    /**
     * Вычисляемое значение долга клиента
     * @return int
     */
    public function getClientDebtAttribute()
    {
        if ($this->is_cashless) {
            return $this->cashbox_debt;
        }
        return $this->cost - $this->prepay - $this->result_amount;
    }

    /**
     * Имеется-ли долг клиента
     * @return boolean
     */
    public function getHasClientDebtAttribute()
    {
        return $this->client_debt > 0;
    }

    /**
     * Имеется-ли долг клиента
     * @return boolean
     */
    public function getHasDebtAttribute()
    {
        return $this->debt > 0;
        //return ($this->has_client_debt || $this->cashbox_master_debt);
    }

    public function getIsCashlessAttribute()
    {
        //echo 'cashless ' . $this->attributes['cashless'];
        return $this->attributes['cashless'] > 0;
    }

    /* public function scopeOfMaster($query, $id)
      {
      return $query->whereCreatedBy($id);
      } */

    public function getTypeDateField($type)
    {
        switch ($type) {
            case 'new':
                return Order::CREATED_AT;
            case 'finish':
                return Order::FINISH_DATE;
            case 'finished':
                return Order::FINISHED_TIME;
            case 'overdue':
                return Order::FINISH_DATE;
            case 'refused':
                return Order::REFUSE_TIME;
            case 'archived':
                return Order::ARCHIVED_AT;
            default:
                return Order::CREATED_AT;
        }
    }

    public function getTypeOptions()
    {
        //$defaultTime = static::getDefaultDateTimeString();

        return [

app/views/order/inc/cashbox.blade.php
<?php
/* @var $order Order */

?>

{{ Form::model($order, array(
                    'url' => $routes['cashbox']['route'],
                    'class' => 'form-horizontal well',
                    'id' => 'order-cashbox-form',
                    'role'=>'form',
                    'method'=>(isset($routes['cashbox']['method'])?$routes['cashbox']['method']:'POST'))) }}

<div class="form-group{{{ $errors->has('cash') ? ' has-error' : '' }}}" id="cash-summ-form">
    {{ Form::label('cash', 'Сдаваемая сумма', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-3 input-group">
        {{ Form::text('cash', Input::old('cash'), array('class' => 'form-control')) }}
        <span class="input-group-addon"> {{$order->currency}}</span>
        <span class="text-danger">{{ $errors->first('cash') }}</span>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
        {{ Form::submit($routes['cashbox']['name'], array('class' => 'btn btn-large btn-primary')) }}
        <button id="reset-button" type="button" class="reset btn btn-primary">Отмена</button>
    </div>
</div>

{{ Form::close() }}



<script>
    $(document).ready(function () {

        var order = <?= $order->toJson() ?>;
        $("#order-cashbox-form").hide();
        $('#data-loading').hide();
        $("#results").hide();
        if (<?= $order->cashbox_debt ?>) {
            $("#close-button").hide();
        } else {
            $("#cashbox-button").hide();
        }

        $("#cashbox-button").click(function () {
            $(this).hide();
            //close_all_forms();
            $("#results").hide();
            $("#order-cashbox-form").show();
            $("#cash").val(function () {
                $(this).val() ? $(this).val() : '';
            });
        });
        $("#cashbox_debt").bind('DOMNodeInserted', function () {
            //alert('cashbox_debt changed');
            if ($("#cashbox_debt span").text() == '0') {
                $("#cashbox-button").prop("disabled", true);
                //alert("#cashbox_debt == 0");
                $("#close-button").show();
            }
        });
        $("#cash").on('input', function () {
            sum = (order.cost - order.cashbox - $(this).val());
            if (sum < 0) {
                alert('Вносимая сумма превышает сумму долга');
                $("#order-cashbox-form :submit").prop("disabled", true);
            } else {
                $("#order-cashbox-form :submit").prop("disabled", false);
                $("#cashbox_debt span").text(sum);
            }
        });
        $("#order-cashbox-form").submit(function () {
            $('#data-loading').show();
            $(this).hide();
            $.ajax({
                type: "POST",
                data: $(this).serialize(),
                dataType: "json",
                cache: false,
                url: '<?= $routes['cashbox']['route'] ?>',
                success: function (data) {
                    if (data.error === false) {
                        order.cashbox = data.data.cashbox;
                        $("#cashbox span").text(data.data.cashbox);
                        $("#cashbox_debt span").text(data.data.cashbox_debt);
                        if (data.data.cashbox_debt == 0) {
                            window.location.replace("<?= route('order.show',
    $order->getKey()) ?>");
                        }

                        $("#results").text('Внесено в кассу: ' + data.data.added + ' ' + '<?= $order->currency ?>')
                                .removeClass('alert-danger')
                                .addClass('alert-success')
                                .show();
                    } else {
                        $("#results").html('Произошла ошибка: ' + data.msg)
                                .removeClass('alert-success')
                                .addClass('alert-danger')
                                .show();
                    }
                    $('#data-loading').hide();
                    $("#cashbox-button").show();
                },
                error: function (jqXHR, textStatus) {
                    $("#results").html('Произошла ошибка: сервер вернул статус ' + textStatus).show();
                    $('#data-loading').hide();
                    $("#cashbox-button").show();
                }
            });
            return false;
        });
    });
</script>

app/views/order/inc/close.blade.php
<?php
/* @var $order Order */

?>

<div id="data-loading" class="well">
    <h4><img src="/img/ajax-loader.gif"/> Обработка данных...</h4>
</div>

<div id="results" class="alert alert-block alert-success">
</div>

<button id="btn-order-close" class="btn btn-primary btn-sm">{{$routes['close']['name']}}</button>

<script>
    $(document).ready(function () {

        var order = <?= $order->toJson() ?>;

        $('#data-loading').hide();
        $("#results").hide();

        if (<?= $order->cashbox_debt ?>) {
            $("#btn-order-close").hide();
        }

        $("#btn-order-close").click(function () {
            if (confirm("Закрыть заказ?")) {
                $('#data-loading').show();
                $(this).hide();
                $.ajax({
                    type: "POST",
                    data: '_token=<?= csrf_token() ?>',
                    dataType: "json",
                    cache: false,
                    url: '<?= $routes['close']['route'] ?>',
                    success: function (data) {
                        if (data.error === false) {
                            $("#results").text("Заказ успешно закрыт")
                                    .removeClass('alert-danger')
                                    .addClass('alert-success')
                                    .show();
                        } else {
                            $("#results").text('Произошла ошибка: ' + data.msg)
                                    .removeClass('alert-success')
                                    .addClass('alert-danger')
                                    .show();
                        }
                        $('#data-loading').hide();
                    },
                    error: function (jqXHR, textStatus) {
                        $("#results").html('Произошла ошибка: ' + textStatus).show();
                        $('#data-loading').hide();
                        $("#btn-order-close").show();
                    }
                });
                return false;
            }
        });
    });
</script>

app/views/order/inc/create_fields_form.blade.php
{{ HTML::style('/css/jquery.datetimepicker.css') }}
{{ HTML::script('/js/jquery.datetimepicker.js') }}

{{ Form::model($entry, array(
                    'route' => $route,
                    'class' => 'form-horizontal',
                    'role'=>'form',
                    'files' => true,
                    'method'=>(isset($method)?$method:'POST'))) }}

{{Form::hidden('id',$entry->id)}}

<!-- cashless form -->
<div class="form-group{{{ $errors->has('cashless') ? ' has-error' : '' }}}" id="cashless-form">
    {{ Form::label('cashless', ' ', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-8">
        {{ Form::checkbox('cashless', 1, Input::old('cashless'), array('class' => '')) }}
        Безналичный расчет
        <span class="text-danger">{{ $errors->first('cashless') }}</span>
    </div>
</div>

<!-- Cost -->
<div class="form-group{{{ $errors->has('cost') ? ' has-error' : '' }}}">
    {{ Form::label('cost', 'Стоимость', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-3 input-group">
        <span class="text-danger">{{ $errors->first('cost') }}</span>
        {{ Form::input('tel', 'cost', Input::old('cost'), array('class' => 'form-control')) }}
        <span class="input-group-addon"> руб.</span>
    </div>
</div>

<!-- Prepay -->
<div class="form-group{{{ $errors->has('prepay') ? ' has-error' : '' }}}" id="prepay-form">
    {{ Form::label('prepay', 'Предоплата', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-3 input-group">
        <span class="text-danger">{{ $errors->first('prepay') }}</span>
        {{ Form::input('tel', 'prepay', Input::old('prepay'), array('class' => 'form-control')) }}
        <span class="input-group-addon"> руб.</span>
    </div>
</div>

<!-- inplace form -->
<div class="form-group{{{ $errors->has('inplace') ? ' has-error' : '' }}}" id="inplace-form">
    {{ Form::label('inplace', ' ', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-7 col-md-6">
        {{ Form::checkbox('inplace', 1, Input::old('inplace'), array('class' => '')) }}
        Ремонт на месте
        <span class="text-danger">{{ $errors->first('inplace') }}</span>
    </div>
</div>

<!-- finish-date-form -->
<div class="form-group{{{ $errors->has('finish_date') ? ' has-error' : '' }}}" id="finish-date-form">
    {{ Form::label('finish_date', 'Дата исполнения заказа', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-7 col-md-6">
        <span class="text-danger">{{ $errors->first('finish_date') }}</span>
        {{ Form::text('finish_date', Input::old('finish_date'), array('class' => 'form-control')) }}
    </div>
</div>

<div class="form-group{{{ $errors->has('stuff') ? ' has-error' : '' }}}">
    {{ Form::label('stuff', 'Материалы', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-7 col-md-6 well">
        <span class="text-danger">{{ $errors->first('stuff') }}</span>
        <div id="stuff-form">
            @if(Input::old('stuff_name'))
            @foreach(Input::old('stuff_name') as $i => $stuff_name)
            {{ addStuffField($i, $stuff_name, Input::old('stuff_quantity')[$i]) }}
            @endforeach
            @endif
        </div>
        <a id="btn-add-stuff" class="btn btn-primary btn-sm" href="#js">Добавить материал</a>
    </div>
</div>

<!-- comment -->
<div class="form-group{{{ $errors->has('comment') ? ' has-error' : '' }}}">
    {{ Form::label('comment', 'Комментарий', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-7 col-md-6">
        <span class="text-danger">{{ $errors->first('comment') }}</span>
        {{ Form::textarea('comment', Input::old('comment'), array('class' => 'form-control', 'size' => '20x4')) }}
    </div>
</div>

<!-- Photo -->
<!--
<div class="form-group{{{ $errors->has('photo') ? ' has-error' : '' }}}">
    {{ Form::label('photo', 'Изображения', array('class' => 'col-sm-4 control-label')) }}
    <div class="col-sm-8 input-group" id="photo-form">
        <span class="text-danger">{{ $errors->first('photo') }}</span>
    </div>
</div>
-->

@include('order.inc.finish_fields_form')


<div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
        {{ Form::submit('Сохранить заказ', ['class' => 'btn btn-large btn-primary col-xs-12  col-lg-3']) }}
    </div>
</div>

{{ Form::close() }}

<script>
    $(document).ready(function () {

        $("#finish-fields-form").hide();
        $("#docs-signed-form").hide();

        //addFileInputFieldTo("#photo-form");
        //addStuffFieldTo('#stuff-form');

        $('#btn-add-stuff').click(function () {
            addStuffFieldTo('#stuff-form');
        });

        $('#finish_date').datetimepicker({
            dayOfWeekStart: 1,
            lang: 'ru',
            format: 'Y-m-d',
            timepicker: false,
            closeOnDateSelect: true,
            minDate: 0
        });
        $("#cashless").change(function () {
            if (this.checked) {
                $("#prepay-form").hide();
                $("#prepay-form input").val('');
                $("#result-amount-form").hide();
                $("#result-amount-form input").val('');
                $("#docs-signed-form").show();
            } else {
                $("#docs-signed-form").hide();
                $("#docs-signed-form input:checkbox").prop("checked", false);
                if (!$("#inplace-form input:checkbox").prop("checked")) {
                    $("#prepay-form").show();
                }
                $("#result-amount-form").show();
            }
        });
        $("#inplace").change(function () {
            if (this.checked) {
                $("#finish_date").val(new Date().dateFormat('Y-m-d'));
                //$("#finish_date").prop("disabled", true);
                $("#finish-fields-form").show();
                $("#prepay-form").hide();
                $("#prepay-form input").val('');
            } else {
                $("#finish_date").val('');
                //$("#finish_date").prop("disabled", false);
                $("#finish-fields-form").hide();
                $("#finish-fields-form input").val('');
                if (!$("#cashless-form input:checkbox").prop("checked")) {
                    $("#prepay-form").show();
                }
                $("#docs-signed-form input:checkbox").prop("checked", false);
            }
        });

        function addStuffFieldTo(elem, key, name_val, qty_val) {
            if (key === undefined) {
                key = '';
            }
            if (name_val === undefined) {
                name_val = '';
            }
            if (qty_val === undefined) {
                qty_val = '';
            }
            $('<div class="input-group" style="margin:3px;"><input type="text" name="stuff_name[' + key + ']" placeholder="название" value="' + name_val + '" />&nbsp;<input type="text" name="stuff_quantity[' + key + ']" placeholder="кол-во" size="8" value="' + qty_val + '" />&nbsp;<a class="btn btn-sm btn-danger remove_item" onclick="$(this).parent().remove()" href="#js"> X </a></div>').appendTo(elem);
        }
    });

    function fileInputChanged(elem) {
        if ($(elem).val() !== '') {
            addFileInputFieldTo("#photo-form");
        } else {
            removeFileInputField(elem);
        }
        //$('<input type="file">').change(fileChangeHandler).appendTo(form);
    }

    function addFileInputFieldTo(elem) {
        $('<p><input type="file" name="photo[]" onChange="fileInputChanged(this);" /></p>').appendTo(elem);
    }

    function removeFileInputField(elem) {
        $(elem).parent('p').replaceWith("");
    }

</script>